### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by iProgYou** [henry-pan/SonusStratos#6]
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
- `GET /api/tracks/:id/comments` this is likely unnecessary because you can just get the comments for a track when you do `GET /api/tracks/:id`

**Comment by henry-pan** [comment]
I've removed `GET /api/tracks/:id/comments`, how does it look now?
