### ISSUE TITLE
Song CRUD MVP

### ISSUE THREAD

**Issue by henry-pan** [henry-pan/SonusStratos#9]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by iProgYou** [comment]
- When I click on the treble clef or the back button after playing a song it breaks the player
- The image I uploaded had slightly different dimensions so it looks a tad wonky. I think you could center the image and take of the edges with css so it doesn't move things around
